Better centralized testing composites (#1)
This pull request makes it easier for external repositories to use
testing actions, becoming more transparent to them and needing to know
less about what is happening inside the composite (toolchain file placed
automatically in its place and Dr. Memory's path being obtained by the
same composite that needs it).
Also, code within the composites that called ctest several different
times is now centralized into a single call in the `run-ctest` action.

diff --git a/.github/composites/memcheck/install-memtool/action.yml b/.github/composites/memcheck/install-memtool/action.yml
--- a/.github/composites/memcheck/install-memtool/action.yml
+++ b/.github/composites/memcheck/install-memtool/action.yml
@@ -1,19 +1,27 @@
 name: "Install Memcheck tool"
 description: "Installs the required memcheck tool for every OS."
 
+inputs:
+  only-export-path:
+    description: "If set, no tool will be installed, only relevant paths will be exported without modification."
+    required: false
+    default: false
 outputs:
   drmemory-bash:
     description: "Full path to Dr. Memory (in bash format)."
-    value: ${{ steps.install-drmemory-bash.outputs.drmemory }}
+    value: ${{ steps.export-drmemory-bash.outputs.drmemory }}
   drmemory-pwsh:
     description: "Full path to Dr. Memory (in Powershell format)."
-    value: ${{ steps.install-drmemory-pwsh.outputs.drmemory }}
+    value: ${{ steps.export-drmemory-pwsh.outputs.drmemory }}
+  toolchain-file-msvc:
+    description: "Full path to the toolchain file needed to compile the project with."
+    value: ${{ steps.toolchain-file.outputs.toolchain-file }}
 
 runs:
   using: "composite"
   steps:
     - name: Install Valgrind (Linux)
-      if: runner.os == 'Linux'
+      if: runner.os == 'Linux' && inputs.only-export-path == 'false'
       shell: bash
       run: |
         if which apt-get; then
@@ -25,17 +33,38 @@ runs:
         fi
 
     - name: Install Dr. Memory (Windows)
-      id: install-drmemory-bash
+      if: runner.os == 'Windows' && inputs.only-export-path == 'false'
+      shell: bash
+      run: choco install drmemory
+
+    - name: Download oolchain file (Windows)
+      id: toolchain-file
       if: runner.os == 'Windows'
       shell: bash
       run: |
-        choco install drmemory
-        echo "drmemory=\"/c/Program Files (x86)/Dr. Memory/bin/drmemory.exe\"" >> "$GITHUB_OUTPUT"
+        target="$GITHUB_WORKSPACE/msvc-memcheck.cmake"
+        url="https://raw.githubusercontent.com/gigabit-clowns/.github/main/.github/scripts/cmake/msvc-memcheck.cmake"
+
+        # Exit non-zero on HTTP errors
+        curl -sSLo "$target" --fail "$url" || {
+          echo "Failed to download $url"
+          curl -sS -I "$url"
+          exit 1
+        }
+
+        echo "Downloaded toolchain file to $target"
+        echo "toolchain-file=$target" >> "$GITHUB_OUTPUT"
+
+    - name: Export Dr. Memory path for Windows (Bash)
+      id: export-drmemory-bash
+      if: runner.os == 'Windows'
+      shell: bash
+      run: echo "drmemory=\"/c/Program Files (x86)/Dr. Memory/bin64/drmemory.exe\"" >> "$GITHUB_OUTPUT"
 
     - name: Export Dr. Memory path for Windows (Powershell)
-      id: install-drmemory-pwsh
+      id: export-drmemory-pwsh
       if: runner.os == 'Windows'
       shell: pwsh
       run: |
-        $path = 'C:\Program Files (x86)\Dr. Memory\bin\drmemory.exe'
+        $path = 'C:\Program Files (x86)\Dr. Memory\bin64\drmemory.exe'
         Add-Content -Path $env:GITHUB_OUTPUT -Value "drmemory=$path"
